# Basic set up
# https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#package-ecosystem

version: 2
updates:

  # Maintain PyPI dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
        interval: daily

  # Dockerfile
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
        interval: daily
